### ISSUE TITLE
Client does not prune `application.db`

### ISSUE THREAD

**Issue by lewdeusdev** [initia-labs/initia#209] opened 2024-06-17 23:06 UTC
**Describe the bug**
The client is not pruning the `application.db` properly. 

After restoring from a snapshot, the `application.db` was initially 60GB, but it has now grown to over 200GB over 5 days despite pruning settings being configured.  This is roughly ~30GB/day in storage growth.

My console logs do not show any pruning errors.  From the screenshot below you can see pruning reduces the disk usage but it is still increasing.

**To Reproduce**
1. Restore from a [Crouton Digital snapshot](https://crouton.digital/services/testnets/initia#snapshot)
2. Set pruning to custom with `pruning-keep-recent = "100"` and `pruning-interval = "17"`.
3. Monitor the size of `application.db` over time.

**Expected behavior**
The `application.db` should be pruned according to the custom settings, maintaining a steady size rather than growing excessively.

**Screenshots**
![image](https://github.com/initia-labs/initia/assets/155594427/524e0881-7211-4bb3-9df5-e50efb9727bc)

**Desktop (please complete the following information):**
`inxi` output
```md
System:
  Host: Ubuntu-2204-amd64 Kernel: 5.15.0-25-generic x86_64 bits: 64 Console: pty pts/3
    Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
Machine:
  Type: Desktop System: Hetzner product: N/A v: 1.0 serial: <superuser required>
  Mobo: ASRockRack model: B565D4-V1L serial: <superuser required>
    BIOS: American Megatrends LLC. v: L0.23 date: 02/23/2022
CPU:
  Info: 16-core model: AMD Ryzen 9 5950X bits: 64 type: MT MCP cache: L2: 8 MiB
  Speed (MHz): avg: 3674 min/max: 2200/5083 cores: 1: 3581 2: 3584 3: 3488 4: 4455 5: 3584
    6: 3511 7: 3582 8: 3301 9: 3588 10: 3581 11: 3592 12: 3572 13: 3584 14: 4479 15: 3586 16: 3581
    17: 3574 18: 3576 19: 3439 20: 4468 21: 3549 22: 3559 23: 3579 24: 3634 25: 3583 26: 3585
    27: 3585 28: 3584 29: 3585 30: 4475 31: 3586 32: 3586
Graphics:
  Device-1: ASPEED Graphics Family driver: N/A
  Display: server: No display server data found. Headless machine? tty: 179x91
  Message: GL data unavailable in console. Try -G --display
Audio:
  Message: No device data found.
Network:
  Device-1: Intel I210 Gigabit Network driver: igb
  IF: enp41s0 state: up speed: 1000 Mbps duplex: full mac: a8:a1:59:c0:b9:d3
  IF-ID-1: docker0 state: down mac: 02:42:30:e4:df:7a
RAID:
  Device-1: md0 type: mdraid level: mirror status: active size: 4 GiB report: 2/2 UU
  Components: Online: 0: nvme0n1p1 1: nvme1n1p1
  Device-2: md1 type: mdraid level: mirror status: active size: 1022 MiB report: 2/2 UU
  Components: Online: 0: nvme0n1p2 1: nvme1n1p2
  Device-3: md2 type: mdraid level: mirror status: active size: 1.97 TiB report: 2/2 UU
  Components: Online: 0: nvme0n1p3 1: nvme1n1p3
  Device-4: md3 type: mdraid level: mirror status: active size: 1.52 TiB report: 2/2 UU
  Components: Online: 0: nvme0n1p4 1: nvme1n1p4
Drives:
  Local Storage: total: raw: 6.99 TiB usable: 3.49 TiB used: 672.06 GiB (18.8%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: MZQL23T8HCLS-00A07 size: 3.49 TiB
  ID-2: /dev/nvme1n1 vendor: Samsung model: MZQL23T8HCLS-00A07 size: 3.49 TiB
Partition:
  ID-1: / size: 1.93 TiB used: 184.33 GiB (9.3%) fs: ext4 dev: /dev/md2
  ID-2: /boot size: 988.7 MiB used: 253.8 MiB (25.7%) fs: ext3 dev: /dev/md1
  ID-3: /home size: 1.5 TiB used: 483.48 GiB (31.6%) fs: ext4 dev: /dev/md3
Swap:
  ID-1: swap-1 type: partition size: 4 GiB used: 4 GiB (100.0%) dev: /dev/md0
  ID-2: swap-2 type: file size: 64 GiB used: 18.31 GiB (28.6%) file: /swapfile
Sensors:
  Message: No sensor data found. Is lm-sensors configured?
Info:
  Processes: 433 Uptime: 669d 19h 25m Memory: 125.73 GiB used: 36.71 GiB (29.2%) Init: systemd
  runlevel: 5 Shell: Bash inxi: 3.3.13
```

**Additional context**
Other file sizes in my `/data` directory:
- `application.db`: 200G
- `blockstore.db`: 41G
- `state.db`: 2.1G
- `evidence.db`: 20K

**Comment by beer-1** [comment] 2024-09-27 05:28
did you also set the `pruning = "custom"` in your app.toml?? and This issue should be raise on cosmos-sdk repo in the future. Currently our partners can see the pruning is workin well. so let me close the issue for now, please revisit here if the problem is still exists.

**Closed by beer-1** 2024-09-27 05:28 UTC
